version: '3'

services:
  database:
    container_name: database
    image: postgres:13.0
    volumes:
      - ./task_2/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
